version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: homestead
      POSTGRES_PASSWORD: example
    ports:
      - 5432
  app:
    image: juniorsntsid/laravelapp:v1
    build: 
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/www
    env_file: '.env'
    environment: 
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: homestead
      REDIS_HOST: cache
    links:
      - db
    depends_on: 
      - db
  web:
    image: juniorsntsid/laravelweb:v1
    build: 
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 8080:80
    links: 
      - app  
  cache:
    image: redis:3.0-alpine
volumes:
  dbdata: 