version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: homestead
    ports:
      - 3306:3306
  app:
    image: juniorsntsid/laravelapp:v1
    build: 
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/www
    env_file: '.env'
    environment: 
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: homestead
      REDIS_HOST: cache
    links:
      - db
    depends_on: 
      - db
  web:
    image: juniorsntsid/laravelweb:v1
    build: 
      context: .
      dockerfile: web.Dockerfile
    ports:
      - 8080:80
    links: 
      - app  
  cache:
    image: redis:3.0-alpine
volumes:
  dbdata: 